/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { OwnableContract } from "./Ownable";
import { TVLContract } from "./TVL";

declare global {
    namespace Truffle {
        interface Artifacts {
            require(name: "Ownable"): OwnableContract;
            require(name: "TVL"): TVLContract;
        }
    }
}

export { OwnableContract, OwnableInstance } from "./Ownable";
export { TVLContract, TVLInstance } from "./TVL";
