/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { OwnableUpgradeableContract } from "./OwnableUpgradeable";
import { ERC165UpgradeableContract } from "./ERC165Upgradeable";
import { IERC165UpgradeableContract } from "./IERC165Upgradeable";
import { ERC1155PausableUpgradeableContract } from "./ERC1155PausableUpgradeable";
import { ERC1155UpgradeableContract } from "./ERC1155Upgradeable";
import { IERC1155MetadataURIUpgradeableContract } from "./IERC1155MetadataURIUpgradeable";
import { IERC1155ReceiverUpgradeableContract } from "./IERC1155ReceiverUpgradeable";
import { IERC1155UpgradeableContract } from "./IERC1155Upgradeable";
import { PausableUpgradeableContract } from "./PausableUpgradeable";
import { TrancheSystemContract } from "./TrancheSystem";
import { TVLContract } from "./TVL";
import { EthPoolTVLContract } from "./EthPoolTVL";
import { IRariFundManagerContract } from "./IRariFundManager";
import { IRariFundTokenContract } from "./IRariFundToken";
import { MigrationsContract } from "./Migrations";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "OwnableUpgradeable"): OwnableUpgradeableContract;
      require(name: "ERC165Upgradeable"): ERC165UpgradeableContract;
      require(name: "IERC165Upgradeable"): IERC165UpgradeableContract;
      require(
        name: "ERC1155PausableUpgradeable"
      ): ERC1155PausableUpgradeableContract;
      require(name: "ERC1155Upgradeable"): ERC1155UpgradeableContract;
      require(
        name: "IERC1155MetadataURIUpgradeable"
      ): IERC1155MetadataURIUpgradeableContract;
      require(
        name: "IERC1155ReceiverUpgradeable"
      ): IERC1155ReceiverUpgradeableContract;
      require(name: "IERC1155Upgradeable"): IERC1155UpgradeableContract;
      require(name: "PausableUpgradeable"): PausableUpgradeableContract;
      require(name: "TrancheSystem"): TrancheSystemContract;
      require(name: "TVL"): TVLContract;
      require(name: "EthPoolTVL"): EthPoolTVLContract;
      require(name: "IRariFundManager"): IRariFundManagerContract;
      require(name: "IRariFundToken"): IRariFundTokenContract;
      require(name: "Migrations"): MigrationsContract;
    }
  }
}

export {
  OwnableUpgradeableContract,
  OwnableUpgradeableInstance,
} from "./OwnableUpgradeable";
export {
  ERC165UpgradeableContract,
  ERC165UpgradeableInstance,
} from "./ERC165Upgradeable";
export {
  IERC165UpgradeableContract,
  IERC165UpgradeableInstance,
} from "./IERC165Upgradeable";
export {
  ERC1155PausableUpgradeableContract,
  ERC1155PausableUpgradeableInstance,
} from "./ERC1155PausableUpgradeable";
export {
  ERC1155UpgradeableContract,
  ERC1155UpgradeableInstance,
} from "./ERC1155Upgradeable";
export {
  IERC1155MetadataURIUpgradeableContract,
  IERC1155MetadataURIUpgradeableInstance,
} from "./IERC1155MetadataURIUpgradeable";
export {
  IERC1155ReceiverUpgradeableContract,
  IERC1155ReceiverUpgradeableInstance,
} from "./IERC1155ReceiverUpgradeable";
export {
  IERC1155UpgradeableContract,
  IERC1155UpgradeableInstance,
} from "./IERC1155Upgradeable";
export {
  PausableUpgradeableContract,
  PausableUpgradeableInstance,
} from "./PausableUpgradeable";
export { TrancheSystemContract, TrancheSystemInstance } from "./TrancheSystem";
export { TVLContract, TVLInstance } from "./TVL";
export { EthPoolTVLContract, EthPoolTVLInstance } from "./EthPoolTVL";
export {
  IRariFundManagerContract,
  IRariFundManagerInstance,
} from "./IRariFundManager";
export {
  IRariFundTokenContract,
  IRariFundTokenInstance,
} from "./IRariFundToken";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
